language: java

# whitelist
branches:
  only:
    - master

# jdk
jdk:
  - oraclejdk8

before_script:
#  - wget http://pnml.lip6.fr/camipnml/download/fr.lip6.pnml.cami2pnml-2.1.13.jar
#  - mvn install:install-file -Dfile=fr.lip6.pnml.cami2pnml-2.1.13.jar -DgroupId=fr.lip6.pnml -DartifactId=fr.lip6.pnml.cami2pnml -Dversion=2.1.13 -Dpackaging=jar
   - chmod 755 ./build.sh
   - chmod +x gradle/wrapper/gradle-wrapper.jar
   - chmod +x gradlew

# script to launch
# le script sh contient juste une commande de build maven. ça pourrait aussi être une commande de build gradle
# exemple: mvn -f pom.xml clean package -Dmaven.javadoc.skip=true -Dmaven.test.skip=true
# Si vous voulez que les tests soient exécutés, enlevez l'option correspondante.

script: "./build.sh"

# cache pour Maven
#cache:
#  directories:
#    - '$HOME/.m2/repository'

notifications:
  slack: 'm1miage-javateam.slack.com:xoxp-534865671954-534705393460-579318650647-66d243f61599d6bf97d484212f8a7c83#github'
    on_success: always
